uhac/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from app import views

urlpatterns = [
    url('api/connect/', views.ConnectView.as_view(), name='api.login'),
    url('api/verify/', views.VerifyView.as_view(), name='api.verify'),
    url('records/create/', views.CriminalRecordCreateView.as_view(), name='records.create'),
    url('records/', views.CriminalRecordView.as_view(), name='records.list'),
    url('register/', views.RegistrationView.as_view(), name='register'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .multichain import api
from hashlib import md5
from json import dumps


class Account(models.Model):
    user = models.ForeignKey(User, related_name='account')
    account_name = models.CharField(max_length=255)
    account_number = models.CharField(max_length=255)


class UserStream(models.Model):
    user = models.OneToOneField(User)
    stream_id = models.CharField(max_length=32)


@receiver(post_save, sender=User)
def create_user_stream(sender, instance, created, **kwargs):
    if created:
        address = api.getnewaddress()
        stream_id = md5(address.encode('utf-8')).hexdigest()
        transaction_id = api.create('stream', stream_id, False)
        if not len(transaction_id) == 64:
            print('invalid transaction id (' + transaction_id + ')')

        user_stream = UserStream(user_id=instance.id, stream_id=stream_id)
        user_stream.save()


@receiver(post_save, sender=Account)
def publish_account_stream(sender, instance, created, **kwargs):
    if created:
        stream_id = instance.user.userstream.stream_id
        data = instance.account_name + '|' + instance.account_number
        api.publish(stream_id, 'account', data.encode('utf-8').hex())

app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms.models import ModelForm
from .models import CriminalRecord, User
from django.forms import DateInput


class CriminalRecordForm(ModelForm):
    class Meta:
        model = CriminalRecord
        fields = ['user', 'offense', 'case_number', 'case_status', 'committed_at']
        widgets = {'committed_at': DateInput(attrs={'type': 'datetime'})}


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name']

app/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, DetailView
from .forms import RegistrationForm, AccountCreateForm
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, render
from .models import UserStream, Account
from django.views import View
from .sdk import client


class LoginRequiredView(View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        # noinspection PyUnresolvedReferences
        return super(LoginRequiredView, self).dispatch(request, *args, **kwargs)


# noinspection PyMethodMayBeStatic
class ConnectView(LoginRequiredView):
    def get(self, request):
        return redirect(client.create_auth_url())


# noinspection PyMethodMayBeStatic
class VerifyView(LoginRequiredView):
    def get(self, request):
        code = request.GET.get('code')
        user_stream = UserStream.objects.get(user=request.user)
        user_stream_id = user_stream.stream_id if user_stream else None
        client.authorize(code, user_stream_id)
        request.session['oauth.access_token'] = client.access_token
        return redirect('account_profile')


class RootView(View):
    def dispatch(self, request, *args, **kwargs):
        return redirect('login')


# noinspection PyMethodMayBeStatic
class AccountsProfileView(LoginRequiredView, DetailView):
    def get(self, request, *args, **kwargs):
        # scopes = []
        accounts = Account.objects.filter(user=request.user)
        access_token = request.session.get('oauth.access_token')
        # if access_token:
        #     client.access_token = access_token
        #     scopes = client.api('/api/')

        return render(request, 'accounts/profile.html', {
            'accounts': accounts,
            # 'scopes': scopes
        })

    def get_context_data(self, **kwargs):
        context = super(AccountsProfileView, self).get_context_data(**kwargs)
        context['accounts'] = self.request.user.account
        return context


class RegistrationView(CreateView):
    form_class = RegistrationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'


class AccountsCreateView(CreateView):
    form_class = AccountCreateForm
    success_url = reverse_lazy('account_profile')
    template_name = 'accounts/create.html'

app/templates/accounts/create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block contents %}
<div class="col-md-offset-3 col-md-6">
    <form class="form-horizontal" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <input id="id_user" name="user" type="hidden" value="{{ request.user.id }}">
        {% for field in form.visible_fields %}
            {% if field.errors %}
                <div class="control-group error">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field|add_class:'form-control' }}
                        <span class="help-inline">
                            {% for error in  field.errors %}{{ error }}{% endfor %}
                        </span>
                    </div>
                </div>
            {% else %}
                <div class="form-group">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field|add_class:'form-control' }}
                        {% if field.help_text %}
                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <div class="row">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/accounts/profile.html
{% extends "base.html" %}

{% block contents %}
    <div class="col-md-offset-3 col-md-6">
        <div class="page-header">
            <h1>My Bank Accounts</h1>
        </div>
        <div class="col-sm-12 table-responsive">
            {% if accounts %}
                <table class="table">
                    <tr>
                        <th>Account Name</th>
                        <th>Account Number</th>
                    </tr>
                    <tr>
                        {% for account in accounts %}
                            <td>{{ account.account_name }}</td>
                            <td>{{ account.account_number }}</td>
                        {% endfor %}
                    </tr>
                </table>
            {% else %}
                <div class="alert alert-warning">
                    You don't have any bank account yet
                </div>
            {% endif %}
        </div>
        <div class="col-sm-12">
            <!--suppress HtmlUnknownTarget -->
            <a class="btn btn-primary" href="/accounts/create/">Create new account</a>
        </div>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>AprilBank PH</title>

        <link href="//bootswatch.com/spacelab/bootstrap.min.css" rel="stylesheet">
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <script src="//oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    </head>
    <body>
        {% include "nav.html" %}
        <div class="container">
            <div class="row">
                <div class="col-sm-12" style="margin-top: 100px">
                    {% block contents %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="/static/js/bootstrap.min.js"></script>
    </body>
</html>

app/templates/nav.html
<!--suppress HtmlUnknownTarget -->
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/records/">AprilBank PH</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {% if request.user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="/accounts/profile/">Accounts</a></li>
                </ul>
            {% endif %}

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="/logout/">Logout</a></li>
                {% else %}
                    <li><a href="/login/">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

app/templates/records/create.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block contents %}
<div class="col-md-6 col-md-offset-3">
    <div class="row">
        <div class="page-header">
            <h3>Create new user's criminal record</h3>
        </div>
    </div>
    <form class="form-horizontal" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input id="id_user" name="user" type="hidden" value="{{ request.user.id }}">
            {% for field in form.visible_fields %}
                {% if field.errors %}
                    <div class="control-group error">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">
                            {{ field|add_class:"form-control" }}
                            <span class="help-inline">
                                {% for error in  field.errors %}{{ error }}{% endfor %}
                            </span>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">
                            {{ field|add_class:"form-control" }}
                            {% if field.help_text %}
                                <p class="help-inline"><small>{{ field.help_text }}</small></p>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        <div class="row">
            <button type="submit" class="btn btn-primary">Create record</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/records/list.html
{% extends "base.html" %}

{% block contents %}
    <h1>Criminal Records List</h1>
    <!--suppress HtmlUnknownTarget -->
    <a href="/records/create/">Create new record</a>

    {% if records %}
        <table class="table table-bordered">
            <tr>
                <th>#</th>
                <th>Person Name</th>
                <th>Offense</th>
                <th>Case Number</th>
                <th>Case Status</th>
                <th>Committed At</th>
            </tr>
            {% for record in records %}
            <tr>
                <td>{{ record.id }}</td>
                <td>{{ record.user.last_name }}, {{ record.user.first_name }}</td>
                <td>{{ record.offense }}</td>
                <td>{{ record.case_number }}</td>
                <td>{{ record.case_status }}</td>
                <td>{{ record.committed_at }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="alert alert-warning">No criminal records as of now</div>
    {% endif %}
{% endblock %}

app/templates/records/profile.html
{% extends "base.html" %}
{% block contents %}
    <div class="col-md-offset-3 col-md-6">
        {% if records %}
            <table class="table table-bordered">
                <tr>
                    <th>#</th>
                    <th>Person Name</th>
                    <th>Offense</th>
                    <th>Case Number</th>
                    <th>Case Status</th>
                    <th>Committed At</th>
                </tr>
                {% for record in records %}
                <tr>
                    <td>{{ record.id }}</td>
                    <td>{{ record.user.last_name }}, {{ record.user.first_name }}</td>
                    <td>{{ record.offense }}</td>
                    <td>{{ record.case_number }}</td>
                    <td>{{ record.case_status }}</td>
                    <td>{{ record.committed_at }}</td>
                </tr>
                {% endfor %}
            </table>
        {% else %}
            <div class="alert alert-warning">No criminal records as of now</div>
        {% endif %}
    </div>
{% endblock %}